#adwords = AdwordsApi::Api.new({
#  :authentication => {
#      :method => 'OAuth2',
#      :oauth2_client_id => "939462896934-j167tods36ru0n94iu0jgodh7gmpqe9k.apps.googleusercontent.com",
#      :oauth2_client_secret => "Q_aanuG49OGc5JWf3sdTcGyv",
#      :developer_token => 'DEVELOPER_TOKEN',
#      :client_customer_id => '012-345-6789',
#      :user_agent => 'Rails Samples'
#  },
#  :service => {
#    :environment => 'DEVELOPMENT'
#  }
#})